# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    # services:
    #   mongo:
    #     image: mongo
    #     env:
    #       MONGO_INITDB_ROOT_USERNAME: test
    #       MONGO_INITDB_ROOT_PASSWORD: password
    #       MONGO_INITDB_DATABASE: test
    #     options: >-
    #       --health-cmd mongo
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 27017:27017   
    # ubuntu-18.04
    # ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Create mongoDB Docker container      
      run: sudo docker run -d -p 27017:27017 mongo:latest    
    - uses: actions/checkout@v1 
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3         
    - name: Run the tests
      run: npm run test
