# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04
    # ubuntu-18.04
    # ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v1 
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3         
    - name: Run the tests
      run: npm run test
